message(STATUS "Checking for MYSQL")
# find_package(Geant4 QUIET COMPONENTS vis_all ui_all)
find_package(MySQL QUIET)
if(NOT MySQL_FOUND)
    message(STATUS "******* MYSQL was not found ******* ")
    message(FATAL_ERROR " ** You will need to setup the MySQL libraries properly **")
else()
    if(APPLE)
        link_directories(${MYSQL_LIB_DIR})
        link_directories("/usr/local/opt/openssl/lib")
        message(STATUS "Added link_directories: ${MYSQL_LIB_DIR}")
    endif()
endif()