message(STATUS "Checking for MYSQL")
# find_package(Geant4 QUIET COMPONENTS vis_all ui_all)
find_package(MYSQL QUIET)
if(NOT Geant4_FOUND)
    message(STATUS "******* MYSQL was not found ******* ")
    error(STATUS " ** NEED to create Mysql auto-install here.")
else()
    if(APPLE)
        link_directories(${MYSQL_LIB_DIR})
        link_directories("/usr/local/opt/openssl/lib")
        message(STATUS "Added link_directories: ${MYSQL_LIB_DIR}")
    endif()
endif()